name: Add carto study issue when new claim issue is closed

on:
  issues:
    types: [closed]

jobs:
  add-issue:
    if: contains(github.event.issue.labels.*.name, 'new_claim')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
        cat study-auto.md >> $GITHUB_EVENT_PATH
